[package]
name = "minotari_wallet"
authors = ["The Tari Development Community"]
description = "Tari cryptocurrency wallet library"
license = "BSD-3-Clause"
version = "1.0.0-pre.13"
edition = "2018"

[dependencies]
strum_macros = "0.22"

[build-dependencies]

[dev-dependencies]

[features]
